# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 484910cf393a6e8015258390b71c685924194bb0d62a36e50766b5e421046de51b60c28caea9825d9407a7437e679e7bef14ed3b669e8b3cc89efd2632bad5f4

test:
  secret_key_base: 34698af18feb104054f437358ffe0a18a67a99770901232aede4e08d89616a2ee6c98e43af153095281b017141e5e9f487aa0043219caa6b67c66c39e6e8d142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
